apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myfirstpvc           # the name of your created pvc
spec:
  storageClassName: standard # the storage class we defined previously
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi # the size of our pvc
