apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pv-name
  annotations:
    pv.kubernetes.io/provisioned-by: csi.vsphere.vmware.com
  labels:
    "app": "tito-app" # a label set
spec:
  storageClassName: standard # the storage class we defined previously
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi # the size of our pvc
