apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adess2
  namespace: default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
