apiVersion: v1
kind: Service
metadata:
  name: titofe-service
  labels:
    app: tito
    tier: frontend
    stage: prod
spec:
  ports:
  - name: http
    port: 80               
  selector:                
    type: tito-fe
    tier: frontend
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.2.4